"""add condition strategy fields

Revision ID: c1c4fbe2a9dc
Revises: 6bf2c7cb3e9a
Create Date: 2026-07-01 19:11:52.824516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1c4fbe2a9dc'
down_revision: Union[str, None] = '6bf2c7cb3e9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sm_strategy', sa.Column('index_trigger', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sm_strategy', sa.Column('vix_condition', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sm_strategy', 'vix_condition')
    op.drop_column('sm_strategy', 'index_trigger')
    # ### end Alembic commands ###
